name: Blog Posts

on:   
    # Run workflow automatically
  schedule:
    # Runs every hour, on the hour
    - cron: '12 8 * * *'
    # workflow_dispatch


jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # comma-separated list of RSS feed urls
          feed_list: "https://readrss.cf/163/music/playlist/552061404"
