name: Blog Posts

on: workflow_dispatch


jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # comma-separated list of RSS feed urls
          feed_list: "https://rssread.tk/bilibili/followings/dynamic/110904497?filterout=中奖|抽奖|下单|拼多多|优惠|优惠劵|深空之眼|眼相关|读剧情|航空|预告|捞|杀死那个"
